config/routes.rb
Rails.application.routes.draw do
 
  resources :deals
  resources :profiles
  resources :products
  resources :offers
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/clear'
  get 'session/debug'

  get 'welcome/landing', :as => :welcome_landing

  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

  root 'welcome#landing'
  
  get 'offers/index'

end

app/views/layouts/_flash.html.haml
- if flash[:notice]
  #notice.alert.alert-info{role: "alert"}
    = flash[:notice]
- elsif flash[:warning]
  #warning.alert.alert-danger{role: "alert"}
    = flash[:warning]

app/views/layouts/_footer.html.haml
<br>
%div
= button_to "Log Out", logout_path, :class => 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %body
    %title Deals4all
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", integrity: "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %nav.navbar.navbar-expand-lg.bg-dark.text-white.mb-5
      %h1
      - unless @action == 'login'
        = link_to " Deals4all ", products_path

      - else
        = link_to "Deals4all", welcome_landing_path 
     
    .container
      = render 'layouts/flash'
      %main#main
        = yield
        - unless @action == 'login'
          = render "layouts/footer"